name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build_tw_iso:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    container:
      image: 'ghcr.io/void-linux/void-mklive:20250116R1'
      options: --privileged
      volumes:
        - /dev:/dev
      env:
        PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin'

    steps:
      - name: Prepare container
        shell: sh
        run: xbps-install -Syu xbps && xbps-install -yu
      - name: Clone and checkout
        uses: classabbyamp/treeless-checkout-action@v1
      - run: ./mktw.sh
